# Generated by Django 4.1.2 on 2023-02-28 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user"),
    ]

    operations = [
        migrations.DeleteModel(name="User",),
    ]
